version: '2'
services:
    proxy:
        image: nginx
        container_name: proxy
        volumes:
            - ./data/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
            - ./data/public/backend-not-found.html:/var/www/html/backend-not-found.html
            - ./data/nginx/includes:/etc/nginx/includes
            - ./data/ssl:/etc/ssl/certs/nginx
        ports:
            - 80:80
            - 443:443
        extra_hosts:
            - "host.docker.internal:host-gateway"
        restart: unless-stopped
